version: '3'
services: 
  gpxmatcher:
    build: 
      context: ./.
    image: gpxmatcher
    container_name: gpx-to-exif
    volumes: 
      - ./source:/data/source
      - ./target:/data/target
      - ./gpxToExif:/gpxmatcher
      - ./resources:/resources
    environment: 
      #Set correct timezone here
      - timezone=2
      #Set default location which is set if no location is found. Name has to be defined in default-locations.json
      - default=home